name: Deploy SESMI-NODEJS To BTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy SESMI-NODEJS to Cloud Foundry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: ğŸ“¦ Install Dependencies
        run: npm install

      - name: ğŸ” Cache Cloud Foundry CLI
        id: cache-cf
        uses: actions/cache@v3
        with:
          path: ./cf
          key: cf-cli-v8-linux64

      - name: Install Cloud Foundry CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install -y cf8-cli
          cf version


      - name: ğŸ› ï¸ Move cf CLI to /usr/local/bin
        run: |
          sudo mv ./cf /usr/local/bin/cf
          chmod +x /usr/local/bin/cf
          cf version

      - name: ğŸ” Login to Cloud Foundry
        run: |
          cf api ${{ secrets.CF_API }} --skip-ssl-validation
          cf auth ${{ secrets.CF_USERNAME }} ${{ secrets.CF_PASSWORD }}
          cf target -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}

      - name: ğŸš€ Push App to Cloud Foundry
        run: |
          cf push --strategy rolling
